{{- define "Certificate-ca" -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-com
spec:
  commonName: OSHCA
  isCA: true
  issuerRef:
    kind: Issuer
    name: workload-cluster-ca-issuer
  secretName: openstack-tls-ca
  organization:
    - OSH
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Certificate-ca" ) }}