{{- define "ConfigMap-scripts" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" ( include "helpers.labels.fullname" $ ) "scripts" }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
data:
{{- include "helpers.files.object_content" ( dict "Global" $ "Source" "scripts" ) | nindent 2 }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "ConfigMap-scripts" ) }}