{{- define "Ingress-openstack" -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: openstack
spec:
  rules:
    - host: openstack.cluster.local
      http:
        paths:
          - backend:
              service:
                name: openstack
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
  tls:
      - hosts:
          - openstack.cluster.local
        secretName: openstack-tls
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Ingress-openstack" ) }}