{{- define "Secret-config" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" ( include "helpers.labels.fullname" $ ) "config" }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
data:
{{- include "helpers.config.object_content" ( dict "Global" $ ) | nindent 2 }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Secret-config" ) }}

