{{- define "Secret-ceph" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" ( include "helpers.labels.fullname" $ ) "ceph" }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
data: null
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Secret-ceph" ) }}

